from dlt.common.schema.utils import new_column

SKLIK_ACCOUNT_SETTING_COLUMNS = {
    "user_id": {"data_type": "text"},
    "username": {"data_type": "text"},
    "agency_status": {"data_type": "text"},
    "access": {"data_type": "text"},
    "wallet_credit": {"data_type": "double", "scale": 2},
    "wallet_credit_with_vat": {"data_type": "double", "scale": 2},
    "wallet_verified": {"data_type": "bool"},
    "relation_name": {"data_type": "text"},
    "relation_status": {"data_type": "text"},
    "relation_type": {"data_type": "text"},
}

SKLIK_CAMPAIGNS_SETTINGS_COLUMNS = {
    "account_id": {"data_type": "text"},
    "account_name": {"data_type": "text"},
    "id": {"data_type": "text"},
    "name": {"data_type": "text"},
    "status": {"data_type": "text"},
    "type": {"data_type": "text"},
    "deleted": {"data_type": "bool"},
    "budget__id": {"data_type": "text"},
    "budget__name": {"data_type": "text"},
    "budget__color_code_id": {"data_type": "text"},
    "budget__day_budget": {"data_type": "bigint"},
    "context_network": {"data_type": "text"},
    "create_date": {"data_type": "text"},
    "delete_date": {"data_type": "text"},
    "start_date": {"data_type": "text"},
    "end_date": {"data_type": "text"},
    "ad_selection": {"data_type": "text"},
    "devices_price_ratio__desktop": {"data_type": "bigint"},
    "devices_price_ratio__mobile": {"data_type": "bigint"},
    "devices_price_ratio__tablet": {"data_type": "bigint"},
    "devices_price_ratio__other": {"data_type": "bigint"},
    "exhausted_total_budget": {"data_type": "bigint"},
    "total_clicks": {"data_type": "bigint"},
    "total_clicks_from": {"data_type": "text"},
    "total_budget": {"data_type": "bigint"},
    "total_budget_from": {"data_type": "text"},
    "video_format": {"data_type": "text"},
}

SKLIK_GROUPS_SETTINGS_COLUMNS = {
    "account_id": {"data_type": "text"},
    "account_name": {"data_type": "text"},
    "id": {"data_type": "text"},
    "name": {"data_type": "text"},
    "status": {"data_type": "text"},
    "campaign__id": {"data_type": "text"},
    "campaign__name": {"data_type": "text"},
    "create_date": {"data_type": "text"},
    "delete_date": {"data_type": "text"},
    "max_cpc": {"data_type": "bigint"},
    "max_cpt": {"data_type": "bigint"},
    "devices_price_ratio__desktop": {"data_type": "bigint"},
    "devices_price_ratio__mobile": {"data_type": "bigint"},
    "devices_price_ratio__tablet": {"data_type": "bigint"},
    "devices_price_ratio__other": {"data_type": "bigint"},
}

SKLIK_GROUPS_STATS_COLUMNS = {
    "date": {"data_type": "date"},
    "account_id": {"data_type": "text"},
    "account_name": {"data_type": "text"},
    "campaign__id": {"data_type": "text"},
    "campaign__name": {"data_type": "text"},
    "id": {"data_type": "text"},
    "name": {"data_type": "text"},
    "impressions": {"data_type": "bigint"},
    "clicks": {"data_type": "bigint"},
    "total_money": {"data_type": "bigint"},
    "conversions": {"data_type": "bigint"},
    "conversion_value": {"data_type": "bigint"},
    "avg_pos": {"data_type": "double", "scale": 2},
    "win_rate": {"data_type": "double", "scale": 2},
    "miss_impressions": {"data_type": "bigint"},
    "exhausted_budget": {"data_type": "bigint"},
    "stopped_by_schedule": {"data_type": "bigint"},
    "under_forest_threshold": {"data_type": "bigint"},
    "exhausted_budget_share": {"data_type": "double", "scale": 2},
    "ish": {"data_type": "double", "scale": 2},
    "ish_context": {"data_type": "double", "scale": 2},
    "ish_sum": {"data_type": "double", "scale": 2},
}

metric_columns = [
    "impressions", "clicks", "total_money", "conversions", "conversion_value",
    "avg_pos", "win_rate", "miss_impressions", "exhausted_budget",
    "stopped_by_schedule", "under_forest_threshold", "exhausted_budget_share",
    "ish", "ish_context", "ish_sum"
]

device_type = ["desktop", "mobile", "tablet", "other"]
new_columns = {k: v for k, v in SKLIK_GROUPS_STATS_COLUMNS.items() if k not in metric_columns}
for device in device_type:
    for metric in metric_columns:
        new_key = f"device_{device}__{metric}"
        new_columns[new_key] = SKLIK_GROUPS_STATS_COLUMNS[metric]

SKLIK_GROUPS_DEVICE_STATS_COLUMNS = new_columns

SKLIK_ADS_STATS_COLUMNS = {
    "date": {"data_type": "date"},
    "account_id": {"data_type": "text"},
    "account_name": {"data_type": "text"},
    "campaign__id": {"data_type": "text"},
    "campaign__name": {"data_type": "text"},
    "group__id": {"data_type": "text"},
    "group__name": {"data_type": "text"},
    "id": {"data_type": "text"},
    "name": {"data_type": "text"},
    "status": {"data_type": "text"},
    "ad_status": {"data_type": "text"},
    "ad_type": {"data_type": "text"},
    "final_url": {"data_type": "text"},
    "create_date": {"data_type": "text"},
    "delete_date": {"data_type": "text"},
    "headline1": {"data_type": "text"},
    "headline2": {"data_type": "text"},
    "headline3": {"data_type": "text"},
    "long_line": {"data_type": "text"},
    "short_line": {"data_type": "text"},
    "description": {"data_type": "text"},
    "description2": {"data_type": "text"},
    "impressions": {"data_type": "bigint"},
    "clicks": {"data_type": "bigint"},
    "views": {"data_type": "bigint"},
    "total_money": {"data_type": "bigint"},
    "conversions": {"data_type": "bigint"},
    "conversion_value": {"data_type": "bigint"},
    "avg_pos": {"data_type": "double", "scale": 2},
    "miss_impressions": {"data_type": "bigint"},
    "under_lower_threshold": {"data_type": "bigint"},
    "exhausted_budget": {"data_type": "bigint"},
    "stopped_by_schedule": {"data_type": "bigint"},
    "under_forest_threshold": {"data_type": "bigint"},
    "exhausted_budget_share": {"data_type": "double", "scale": 2},
    "ish": {"data_type": "double", "scale": 2},
    "ish_context": {"data_type": "double", "scale": 2},
    "ish_sum": {"data_type": "double", "scale": 2},
    "viewership_rate__first_quartile": {"data_type": "double", "scale": 2},
    "viewership_rate__midpoint": {"data_type": "double", "scale": 2},
    "viewership_rate__thirdQuartile": {"data_type": "double", "scale": 2},
    "viewership_rate__complete": {"data_type": "double", "scale": 2},
    "skip_rate": {"data_type": "double", "scale": 2},
}

SKLIK_BANNERS_STATS_COLUMNS = {
    "date": {"data_type": "date"},
    "account_id": {"data_type": "text"},
    "account_name": {"data_type": "text"},
    "campaign__id": {"data_type": "text"},
    "campaign__name": {"data_type": "text"},
    "group__id": {"data_type": "text"},
    "group__name": {"data_type": "text"},
    "id": {"data_type": "text"},
    "banner_name": {"data_type": "text"},
    "status": {"data_type": "text"},
    "ad_status": {"data_type": "text"},
    "ad_type": {"data_type": "text"},
    "image_type": {"data_type": "text"},
    "create_date": {"data_type": "text"},
    "delete_date": {"data_type": "text"},
    "image__width": {"data_type": "bigint"},
    "image__height": {"data_type": "bigint"},
    "impressions": {"data_type": "bigint"},
    "clicks": {"data_type": "bigint"},
    "total_money": {"data_type": "bigint"},
    "conversions": {"data_type": "bigint"},
    "conversion_value": {"data_type": "bigint"},
    "avg_pos": {"data_type": "double", "scale": 2},
    "miss_impressions": {"data_type": "bigint"},
    "exhausted_budget": {"data_type": "bigint"},
    "stopped_by_schedule": {"data_type": "bigint"},
    "under_forest_threshold": {"data_type": "bigint"},
    "exhausted_budget_share": {"data_type": "double", "scale": 2},
    "ish": {"data_type": "double", "scale": 2},
    "ish_context": {"data_type": "double", "scale": 2},
    "ish_sum": {"data_type": "double", "scale": 2},
}

SKLIK_RETARGETING_STATS_COLUMNS = {
    "date": {"data_type": "date"},
    "account_id": {"data_type": "text"},
    "account_name": {"data_type": "text"},
    "campaign__id": {"data_type": "text"},
    "campaign__name": {"data_type": "text"},
    "group__id": {"data_type": "text"},
    "group__name": {"data_type": "text"},
    "retargeting_id": {"data_type": "text"},
    "name": {"data_type": "text"},
    "users": {"data_type": "bigint"},
    "impressions": {"data_type": "bigint"},
    "clicks": {"data_type": "bigint"},
    "total_money": {"data_type": "bigint"},
    "conversions": {"data_type": "bigint"},
    "conversion_value": {"data_type": "bigint"},
    "avg_pos": {"data_type": "double", "scale": 2},
    "miss_impressions": {"data_type": "bigint"},
    "exhausted_budget": {"data_type": "bigint"},
    "stopped_by_schedule": {"data_type": "bigint"},
    "under_forest_threshold": {"data_type": "bigint"},
    "exhausted_budget_share": {"data_type": "double", "scale": 2},
    "ish": {"data_type": "double", "scale": 2},
    "ish_context": {"data_type": "double", "scale": 2},
    "ish_sum": {"data_type": "double", "scale": 2},
}

SKLIK_QUERIES_STATS_COLUMNS = {
    "date": {"data_type": "date"},
    "account_id": {"data_type": "text"},
    "account_name": {"data_type": "text"},
    "campaign__id": {"data_type": "text"},
    "campaign__name": {"data_type": "text"},
    "group__id": {"data_type": "text"},
    "group__name": {"data_type": "text"},
    "group__max_cpc": {"data_type": "bigint"},
    "keyword__id": {"data_type": "text"},
    "keyword__name": {"data_type": "text"},
    "keyword__status": {"data_type": "text"},
    "keyword__match_type": {"data_type": "text"},
    "keyword__max_cpc": {"data_type": "bigint"},
    "keyword__cpc": {"data_type": "bigint"},
    "keyword__url": {"data_type": "text"},
    "query": {"data_type": "text"},
    "avg_cpc": {"data_type": "double", "scale": 2},
    "avg_pos": {"data_type": "double", "scale": 2},
    "impressions": {"data_type": "bigint"},
    "clicks": {"data_type": "bigint"},
    "total_money": {"data_type": "bigint"},
    "conversions": {"data_type": "bigint"},
    "conversion_value": {"data_type": "bigint"},
}
