[project]
name = "unified-sources"
version = "0.2.0"
description = "DLT sources for Unified Reporting"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dlt[duckdb]>=1.11.0",
]

[dependency-groups]
google-ads = [
    "google-ads>=27.0.0",
]
seznam-sklik = [
    "sklik>=1.0.6",
]
